### ISSUE TITLE
Needs Glyphs 3 support

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/Show-Distance-And-Angle-Of-Nodes#10]
Crashes when active according to user report.

**Comment by schriftgestalt** [comment]
Please update the binary `MacOS/plugin` from https://github.com/schriftgestalt/GlyphsSDK/tree/Glyphs3/Python%20Templates. (has to be 120kB instead of 21kB). It should fix the crash in Big Sur.
