### ISSUE TITLE
Glyphs 3180 breaks `drawAtPoint_color_alignment_`

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/Show-Distance-And-Angle-Of-Nodes#11]
https://github.com/Mark2Mark/Show-Distance-And-Angle-Of-Nodes/blob/cbe788a9d904ad02380e62f273299a12e8d3679e/ShowDistanceAndAngleOfNodes.glyphsReporter/Contents/Resources/plugin.py#L221

now spits out
```py
AttributeError: '__NSCFString' object has no attribute 'drawAtPoint_color_alignment_'
```

It worked until incl. 3179

Reported [by a user in the forum](https://forum.glyphsapp.com/t/3180-distance-angle-plugin-values-not-showing/25262) as not showing text.

@schriftgestalt do you know what you changed in Glyphs? Was that a category, that you changed? I see that you added that method in the past, and it’s not part of NSString.

**Comment by orioncactus** [comment]
Hello! Any updates? It still has the problem on Glyphs 3182, arm64, macOS 13.3:

<img width="1823" alt="스크린샷 2023-03-30 오후 10 15 31" src="https://user-images.githubusercontent.com/7247848/228847945-d03875a8-e530-44dc-ada7-2927985c7cb7.png">

**Comment by orioncactus** [comment]
I'm still stuck on 3151 due to this problem. I really hope that this issue can be resolved. Thank you so much for your attention 🥺

**Comment by schriftgestalt** [comment]
This is fixed now.

**Comment by Mark2Mark** [comment]
Thanks a lot, Georg!

**Comment by orioncactus** [comment]
Thank you for solving the issue! Everything works now!
