### ISSUE TITLE
Fix angles

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/Show-Distance-And-Angle-Of-Nodes#5]
Test shape: diamond. Angles seem to be 3 * 45° and 1 * 135°

**Comment by schriftgestalt** [comment]
That is easy to fix. Always do:
```
angle = angle % 360
```

**Comment by Mark2Mark** [comment]
Thank you! I’ll change this accordingly :)

**Comment by Mark2Mark** [comment]
I chose to use `% 180` instead, because the directions doesn’t matter, IMO. There won’t be any negative angle values in this case, which I think is ok :)
But thanks for the marvellous tip!

**Comment by schriftgestalt** [comment]
I added some refinement on the badge drawing.

**Comment by Mark2Mark** [comment]
Thank you @schriftgestalt!
