### ISSUE TITLE
Plugin doesn’t work properly on some machines

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/Show-Distance-And-Angle-Of-Nodes#6]
Transferring the [GlyphsApp Forum Thread](https://forum.glyphsapp.com/t/show-distance-and-angle/8176/36) here.

**Comment by Mark2Mark** [comment]
So since I cannot reproduce the issue, I think I’ll have to wait if @schriftgestalt has a tip for me.
To recap: `selectedLayerRange` throws an error, and on another Mac the plugin doesn’t even return any tracebacks even though it should. The user’s could confirm that they got the latest plugin version 1.0.5

**Comment by schriftgestalt** [comment]
I pushed an update. Can you try?

**Comment by Devanatha** [comment]
I just deinstalled and reinstalled the plugin on both my Macbooks, with the same result: The plugin behaves like the original version, with no context menu. Nothing was output to the macro panel, like before.

**Comment by Mark2Mark** [comment]
@sindrebr I pushed another update after Georg’s. Sorry for all the hassle! Baby steps, as I said.

Which Glyphs build are you running on which machine, again, please?

**Comment by hbeier** [comment]
It’s working for me \o/

![screen shot 2018-02-20 at 13 00 37](https://user-images.githubusercontent.com/10968309/36434583-1c13ac5e-163e-11e8-9471-aa20597a4eb2.png)

**Comment by schriftgestalt** [comment]
@sindrebr can you remove the plugins and restart Glyphs and make sure it is actually gone. I have the hunch that you have different versions installed in and the old version is refusing to let go.

**Comment by sindrebr** [comment]
> Which Glyphs build are you running on which machine, again, please?

I'm running Glyphs 2.5b build 1116 (current cutting edge build) on a MacBook Pro Retina, 15-inch, Mid 2015 running Sierra 10.12.6 and the same Glyphs build on a MacBook Pro Retina 13-inch, Late 2012 running High Sierra 10.13.2. 

I just tried reinstalling again, on both machines. Same result, plugin behaves like original version. Maybe some kind of curse.

**Comment by schriftgestalt** [comment]
Did you restart Glyphs and checked that the plugins are actually gone after deinstalling them?

**Comment by sindrebr** [comment]
> Did you restart Glyphs and checked that the plugins are actually gone after deinstalling them?

Yes, numerous times on both machines. I have also removed the files manually a couple of times.

**Comment by Mark2Mark** [comment]
@sindrebr Does it still refuse to print the its name along with its version into the macro panel?

**Comment by sindrebr** [comment]
@Mark2Mark Yes, it is as empty as always. I think I will try do deinstall and reinstall Glyphs itself, to see if that helps.

**Comment by Mark2Mark** [comment]
I am so sorry for all that. :/

**Comment by sindrebr** [comment]
I did a clean install of Glyphs, and lo and behold! It works! I can't understand how all this happened, but now the problem is solved on my part.

**Comment by sindrebr** [comment]
... and the plugin is everything I wanted. Thank you so much again for making this, and for rewriting it after my suggestion.

**Comment by Mark2Mark** [comment]
Thanks for all your patience and the quick responses! Happy to hear that it works now. I have no idea either what could have caused that.
You’re welcome, it was a reasonable suggestion, so I’m happy to implement it. It’s supposed to be a useful tool, so thanks for that.

**Comment by Mark2Mark** [comment]
And @schriftgestalt Thank you too! Next beers or coffees on me :)
